#!usr/bin/env python3

# ················································································· #

# Imports
import argparse
import pandas as pd
import numpy as np


# ················································································· #

def calc_tada(schroprotdesc_csv: str,
              output_tsv: str=None):
    """
    Takes the path to a Protein Descriptors CSV file,
    returns the Therapeutic Antibody Developability Analysis (TA-DA) [https://doi.org/10.1080/19420862.2022.2080628] measure from AbbVie.
    Writes the results to TSV if ``output_tsv`` is provided

    :param: schroprotdesc_csv: Path to a Protein Descriptors CSV, generated by Schrodinger through the Calculate Protein Descriptors Task.
    :returns: If no ``output_tsv`` is specified, a pandas dataframe of TA-DA scores. If ``output_tsv`` is specified, this series is written to file.
    """
    
    # Loading data
    schro_prot_desc = pd.read_csv(schroprotdesc_csv, index_col=0)

    # Defining parameters and variables for TA-DA
    beta0 = 0.542
    betas = np.array([-0.014, -0.023, -0.004, -0.080, -0.007])
    X = schro_prot_desc[['FR_AggScore', 'LFR1_AggScore', 'CDRL_Positive_Patch_Energy', 'Disorder_Propensity_TOP_IDP', 'All_Atomic_Contact_Energy']].values
    
    # Computing TA-DA score
    tada = 1 / (1 + np.exp(-(beta0 + np.sum(betas[None,:] * X, axis=1))))
        
    tada = pd.DataFrame({'TA-DA': tada}, index=schro_prot_desc.index)

    # Returning or writing results
    if output_tsv is None:
            return tada
    else:
        tada.to_csv(output_tsv, sep='\t')

# ················································································· #

if __name__ == '__main__':
    
    # Parsing input arguments
    parser = argparse.ArgumentParser(
        prog='calc-tada',
        usage='''
            python calc-tada.py
                [-h]
                -i/--schroprotdesc-csv  PROTEIN_DESCRIPTORS.CSV
            [   -o/--output-tsv         OUTPUT.TSV              ]
                ''',
        description="Calculate TA-DA developability scores from a Schrodinger Protein Descriptors file (See of ``schrodinger-prot-desc``).",
        epilog='// Frederik Espersen Knudsen, 2025')

    parser.add_argument('-i', '--schroprotdesc-csv',
                        type=str,
                        required=True,
                        help="Path to a Protein Descriptors dataframe, generated by Schrodinger through the Calculate Protein Descriptors Task.")
    parser.add_argument('-o', '--output-tsv',
                        type=str,
                        required=False,
                        default='tada.tsv',
                        help="The path to write the output TSV file to. (Defaults to tada.tsv)")

    args = parser.parse_args()

    # ············································································· #

    # Parsing ANARCI output files
    calc_tada(**vars(args))